# Generated by Django 4.2 on 2025-12-28 10:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True, verbose_name="TMDB ID")),
                ("name", models.CharField(max_length=100, verbose_name="类型名称")),
            ],
            options={
                "verbose_name": "电影类型",
                "verbose_name_plural": "电影类型",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True, verbose_name="TMDB ID")),
                ("title", models.CharField(max_length=200, verbose_name="电影标题")),
                (
                    "original_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="原始标题"
                    ),
                ),
                ("overview", models.TextField(blank=True, verbose_name="剧情简介")),
                (
                    "release_date",
                    models.DateField(blank=True, null=True, verbose_name="上映日期"),
                ),
                (
                    "runtime",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="片长(分钟)"
                    ),
                ),
                ("popularity", models.FloatField(default=0.0, verbose_name="流行度")),
                (
                    "vote_average",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="评分",
                    ),
                ),
                ("vote_count", models.IntegerField(default=0, verbose_name="评分人数")),
                (
                    "poster_path",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="海报路径"
                    ),
                ),
                (
                    "backdrop_path",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="背景图路径"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        related_name="movies",
                        to="movies.genre",
                        verbose_name="电影类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "电影",
                "verbose_name_plural": "电影",
                "ordering": ["-popularity"],
            },
        ),
        migrations.CreateModel(
            name="MovieCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(verbose_name="TMDB ID")),
                ("name", models.CharField(max_length=200, verbose_name="姓名")),
                (
                    "character",
                    models.CharField(blank=True, max_length=200, verbose_name="角色"),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=100, verbose_name="部门"),
                ),
                (
                    "job",
                    models.CharField(blank=True, max_length=100, verbose_name="职位"),
                ),
                (
                    "credit_type",
                    models.CharField(
                        choices=[("cast", "演员"), ("crew", "工作人员")],
                        max_length=10,
                        verbose_name="类型",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "profile_path",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="头像路径"
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="movies.movie",
                        verbose_name="电影",
                    ),
                ),
            ],
            options={
                "verbose_name": "电影演职人员",
                "verbose_name_plural": "电影演职人员",
                "ordering": ["credit_type", "order"],
                "unique_together": {("movie", "tmdb_id", "credit_type")},
            },
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["tmdb_id"], name="movies_movi_tmdb_id_0e4cad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["title"], name="movies_movi_title_652549_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["release_date"], name="movies_movi_release_b7ac7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["popularity"], name="movies_movi_popular_114287_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["vote_average"], name="movies_movi_vote_av_ca6eee_idx"
            ),
        ),
    ]
